### ISSUE TITLE
角色授权问题

### ISSUE THREAD

**Issue by weftii** [bill1012/AdminEAP#14]
角色授权后，赋予用户该角色，登陆后无效，依旧显示所有功能

**Comment by weftii** [comment]
查看你的演示项目，权限部分正常，是不是我的项目那边没配置对？

**Comment by bill1012** [comment]
目前默认是显示所有菜单 在首页改掉获取菜单得路径 路径在loginController中有

**Comment by bill1012** [comment]
在数据库中设置用户isSuperAdmin为空

**Comment by weftii** [comment]
在数据库中设置用户的isSuperAdmin字段为空串并没有解决 希望江哥再提点一下啊
