### ISSUE TITLE
工作流部分是用什么来做的呢？

### ISSUE THREAD

**Issue by rogerfanrui** [bill1012/AdminEAP#2]
clone了代码之后 没有工作流相当的说明，请问一下这个模块暂时还没开放么？

**Comment by bill1012** [comment]
activiti，除了工作流之外，都开源

**Comment by rogerfanrui** [comment]
嗯。页面上的工作流流程编辑能提供一个思路么 感谢

**Comment by bill1012** [comment]
你可以参考这篇文章 http://blog.csdn.net/runming56/article/details/37807589

**Comment by rogerfanrui** [comment]
好的 感谢
发自网易邮箱大师
在2017年07月19日 18:15，billJiang 写道： 你可以参考这篇文章 http://blog.csdn.net/runming56/article/details/37807589

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bill1012/AdminEAP","title":"bill1012/AdminEAP","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bill1012/AdminEAP"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bill1012 in #2: 你可以参考这篇文章 http://blog.csdn.net/runming56/article/details/37807589"}],"action":{"name":"View Issue","url":"https://github.com/bill1012/AdminEAP/issues/2#issuecomment-316339759"}}}
