### ISSUE TITLE
 AdminEAP-web 安装时候出错

### ISSUE THREAD

**Issue by 15863004186sunchi** [bill1012/AdminEAP#40]
![image](https://user-images.githubusercontent.com/19647047/48065659-492a7300-e206-11e8-872a-19242de30286.png)
最后一步安装的时候报错，这个包没有

**Comment by bill1012** [comment]
请严格按照文档安装，AdminEAP-web工程依赖了AdminEAP-framework，所以需要在AdminEAP-framework目录下执行 mvn install，以生成AdminEAP-framework-1.0-SNAPSHOT.jar
